# As much as possible, this file should be kept in sync with
# https://github.com/napari/docs/blob/main/.github/workflows/build_and_deploy_docs.yml
name: Build PR Docs

on:
  push:
    branches:
      - docs
    tags:
      - 'v*'
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - '.github/workflows/build_docs.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-upload:
    name: Build & Upload Artifact
    runs-on: ubuntu-latest
    env:
      XDG_CACHE_HOME: ${{ github.workspace }}/.cache
    steps:
      - name: Clone docs repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: docs  # place in a named directory
          repository: napari/docs

      - name: Clone main repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: napari  # place in a named directory
          # ensure version metadata is proper
          fetch-depth: 0

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
          cache-dependency-path: |
            napari/pyproject.toml

      - name: Cache pooch downloads
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v4
        with:
          path: |
            ${{ github.workspace }}/.cache/scikit-image
            ${{ github.workspace }}/.cache/napari-*
            ${{ github.workspace }}/.cache/pooch
          key: pooch

      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@7d84ae825e6d9297a8e99bdbbae20d1b919a0b19 # v4.2
        with:
          qt: true
          wm: herbstluftwm

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "napari/[pyqt5, docs]"
        env:
          PIP_CONSTRAINT: ${{ github.workspace }}/napari/resources/constraints/constraints_py3.12_docs.txt

      - name: Testing
        run: |
          python -c 'import napari; print(napari.__version__)'
          python -c 'import napari.layers; print(napari.layers.__doc__)'

      - name: Build Docs
        run: make -C docs html
        env:
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
          GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
          PIP_CONSTRAINT: ${{ github.workspace }}/napari/resources/constraints/constraints_py3.12_docs.txt

      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: docs
          path: docs/docs/_build/html
